[package]
name = "borg"
version = "0.1.0"
authors = ["Trim Bresilla <trim.bresilla@gmail.com>"]
description = "a command line tool for ROS2"
edition = "2021"



[dependencies]
anyhow = "1.0.75"
clap = { version = "4.3.23", features = ["derive"] }
getset = "0.1.2"
colored = "2.0.4"
