name: Build

on:
  release:
    types: [created]

jobs:
  release:
    env:
      TOOLCHAIN_VERSION : 1.70.0
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2023-08-01
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v0-rust"
      - run: cargo build --release
      - name: get_current_time
        id: get_current_time
        run: echo "::set-output name=now::$(date +'%s')"
      - name: Upload Archive Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/release/borg
          asset_name: borg-${{ github.event.release.tag_name }}-${{ steps.get_current_time.outputs.now }}-${{ github.sha }}.tar.gz
          asset_content_type: application/gzip
      - name: Upload Binary Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/release/borg
          asset_name: borg-${{ github.event.release.tag_name }}-${{ steps.get_current_time.outputs.now }}-${{ github.sha }}
          asset_content_type: application/octet-stream